### ISSUE TITLE
Add extensive deployment documentation

### ISSUE THREAD

**Issue by jcohenadad** [coda-platform/guides-and-policies#6]
@louismullie shared a very useful stack of slides to explain how to deploy CODA. I suggest making this documentation available under the 'deployment' section of the documentation.

Also also suggest making the source of these slides available for the core dev team. Eg: if a modification is needed, everyone in the core dev team will be able to make that modification (ie: decentralized maintenance).

Related to #3

**Comment by louismullie** [comment]
Hi @jcohenadad 

Here is the link to the slides on GitHub: https://github.com/coda-platform/guides-and-policies/tree/main/guides/deployment

I just shared the Google Slides link to a collaborative version on Slack.

@fmarois is going to tackle the deployment guide for the Ansible deployment.

**Comment by jcohenadad** [comment]
Thank you @louismullie. I think we can close this issue then
